language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: H0nHpYLuYzbFmC7TtnBIoG6zRZGukyyqJs+DWyP2DnTXMHA8P5bdSuB1ASXm88/eQxKQxXBXDnwWN4TUN1RdbWvyttmSMfahSKA8Qd+aMqu8OyhT9nAwdcpO39NJEP5Urhu5nQrMgOXPu9Fa64Ok6wjo33rx+bX3a9ydoaf66/LbVeSsTSaImrmL1qRtyfUJgAaeBf/jX8uqTDdkovCAA5S3/hFR9Xdu1Z0GDU03pbayjaH6QJmLMmQCtQ3y4Ubr0q0iKJZogkIY8a7BbTHa3YK6r0SkQLWtMxOcU6VwMU4EPgRHdcVhkJjDldt/L/6jahTdZ1m7pePCGkTDY85LdWkTfHpfqskymMJYLhWdgWgM/3WSydsd0fcjEoea+yovHgAJ0ockWSLQPyBKm0fSqvuo8GEGchHMCFiVfe4FI6Nujina8tbPbj9xD09YbzPQ9lexChlrLSWUFHNWzOjiRLhTcdWW2vEm/0V5rPvDUnKFY/SCe+Smncu2Uqoy2WvffXIlQI8pU4YxJ1WWkOKj6CLsyfBDECL17HcQPPqdQDILNp5E//CC0xPAhsAanHMef/nRSzMbNTXUUWry33K2M8xiJrslaBK/11h2+y+mfP4EH6c9Ywp90j1FKTw2J00W6FhzKQx6fC0eusCXdVs9YRv1GLI5uXZoM5J0EBZw750=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
