language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: wD0wtlZL5ywK5laklPOraspOv33dXOd6kCi4EeMwZhyzw+ed1zIzNJ/rx9UPa6sPCpzj3W9L66MyNAQOpNPLzxPleOLj5QSD8s+HswPs+Bb+v8QA+WE1NGehq8qssInD9zlAiHghbfZ7Jdodu4aGMGj0pgKFSpTEGXRMhn8lgebT9xbRvaphZeQD059HhKCG5tQVeph2NsXgt2sPpshBdOI1rUTYbI37Y0L6/JndIdGu+l00vz6w/zf2befMzjz48s8v6bNrwJcE9LihMKZQQffnemaT1rSdkYDV/10/UbvyS8oIMoWmKrw8sm7IZ5RK9HEgKUHPvm9aK2qYEscnnC/H8gkPvv5ksRpPkioDMK8CM++P4/9pqe6X95e6DOiALoCqhxMfSEidVQ2pUjHrgp1rH6ENLgOGhheLCKcdvWa+nFkMEl1yyG3ZEyegQZT7wBB+iz1pdjHsINDGRM7rVT8Nekp8TvitV4Aj6wVPyzEGRLT0sAbfARqcWLFGCrm2YCVUewHxy+GJgmJB+u/6kUxhZk0fUnOuuMYXSUU1/3rKtzfR9BvyQyFUv015Eq0mGHZdRWWu9FVtrZ+a40eG0v/ZLsuslz2Whu0xwd/2tnvB8NqSGzOn/3u2IPqj13bTEIwY5FCp5FKsQ50zfrXEaZF4nNWsAd9tc0+tgmxrpYg=
  provider: heroku
