language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: u9fe+4rC6ryfOje+zKUfNxVBmdzzfjqaFS1fHmHq+Z+sfpcNXVNmueXsulOfWuWkz1A0Yz7U6TOurLXGJd8PF9AULoZnfjacBLKsnCtQA3m15IAQw1F3GLg0IsBCPFq+v8+mBha+YFXmxOf8JisZ+LF0IRnRphQyPpbngXBAUjJ3f/4lzg8l2FiIzo+T8eJ4/U+UdoMeO66b8ThFqqhJR75C25QJOTwOdtwjWe0GlF1Zsa1GFw5Oze/PSncrdMvuPMZAzFpMGJEmDcUozmst4tF8/+BAs6/cQpPGqd6lGRtEx7LeBiPOE+faSaU7p2BFEBWi+Lw5r4aqPtcApMEY2JCCzg3x85rqvfduYsuJ/gKlg53YFkQIauTzxU/cBjG/R7l0m5c3w1oVkgFhPTHrmD/Tc4ajf5SlxU/ZCLufrtHG1BKgd5FEiT2Z/XVH4ISk/ZD6UC2QBgW1J+hW8zL8CsO13Pa7ZnYTPorBMapLZpX0AXtC8gUynYbnDU+PPnDCEAWzIGn0mvo9dwdFN4vQZjpy2jvvmiww+N+MlK2OH2Q/GsFArwJqU3GapF7jy7Ucc5F63Tft7BQKyT0zEDNFbYqYbpqyVSPhrqyoI+XrLW1LH4QTPXjBDP3SSHEoFvB375LbpnCgaSfk4VLJD6zYRbSbkpKZj/4+MBH8ASWMYio=
