language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: FhrMYy8YO7geosQuJfI2A+rDBZzuPurNSbwE6L7YXKLGUXDOdKe6a0gAjUP2wZ0/OBgt8IfBrnidTVyoLSRYyoIGAbNTKNLasWeTEsfky96aFCRoESLr4rtLTisp1Mi5YaoSrhzyT2pzEXasjd6TteVFEzsli9vF9L4EDhOb5ehKWwv+j240qbKiaTqdLZS8YgiQC5VydR2jTDkUsP3vCbuP+QZ79IzaUe53Ap/zCvRqF+ouuZH3tOWaqWTnfXBeQ5G3W4zepjv/aqeO9WM7GCeuI6A+uPg6rZll3HkhT4Sy32lWgwYByHf4ZMKIGlkR+PUYEMaJ8VX8SdAkd3rR4j+JyunkmwoFEFuuXGFoiIav68rWW4t0uTEiQ+9O+0h6eTlhMgqm9EVMTSzJifJ7SOj5VrFv2W9YfkHAwGkhoaMqJRmU0gDVG0F04oIxmphHKuuRYLg2xDNycQb50Q79N4T3eJ60qDsK0BBQOH8ahpNVaMSg7wKzwh5MvBTTKBYukXVUPE8pbj4AmX+BhI7WRCgp3TZBgvo+EX9SWrRCOQARU/S0wmWtfL82yVxXC7K5+g5c9dxOF2ITVMF/hLLnZRB6q5n9oX6KzCI8ROi5o0V7d4SjzlHvuPtk1hxe0GaHkLm7h41BL4eQW+8op2ChXAcKAI1P+uyjgVbwnhuqIBs=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
