language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: zSXiZLRlP8nKtDoc6ozlsdBt3btA9aR6PYwdrkyfanbEcyWa0Orku3+PkcE9T6NsflTQkQxA0s9aqTsHHp5N5a3MB11uSpqbzHLK7WAX+A7uR1Oe3HJrypFkLyP1Zn9b0vo2jfFANveeoQ54BZz89ddxeASueuw+V7OKMH7zKmJ1+kOLEvlrr0QDwfiXy8MCHin42ER/CJmCb7nbzQ2qR4hOeoS56e7/A2xW5Xzl84JVm5Q5EFoiSoVDbDO0uwNXB3bA8g/xTC/E/tN2xRiuQYERiSvA4Rtg195J6XF6vTYOjad6iCsmolL3D1H3wKk0vB6b5actiyCw52LU0R+3e21y3Oe5MohzuOuBApy1rEaxgi9HwQUhgyOlg1GbHqSknFMLb8a2VsOf51ktTn7AzgHkHCdjelGSgdzeW3a6FgEMNQ767h6pTrnOyXzA5na1RNnHGVdDXh4d2Au2E6YhNdPcIr4keTqjKbZJ9lIGpt/vOupTTmzteTkzKNQ1qSLiLqkupYFnRGT0U2D8aZtITXjQIZobeWS5GUc3GdLZNDwijAPJs0kBgymhWbFDY+/KKtTLe2aN1AvMUEYeTqKemYegTF0uPefEb/Xb+FbDvBnbdiGiCagUC2dznCK5BFKkcXg4LWj6Jpr6EfDzC7DSAsKurEf58ZDGTBzbaAirVI4=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
