language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: onxEdnIy6J/Mxkm5Hp6/7eEeJrS7aO0xGk9LXsuEuEIS7ERUH+VGprckUNQh+RRjURL/OaqJPqhFFVoebrqCqXJGBl5CkYYNQnM8mwaYuOYlQcOoSkM5GW7jDXe+9GGNEediRk3q+iBHKSWKSnk8J1EsakPAHBQKtO9xy6tXTg2awleZg1+OvplM7LiaEn7VRzNRI6pYD5wxMQ7jQq2V+gujTaq3UKAvNBQf/y0U+9dnvdGL12p+QMPWd9FoHP1PRk8S4WATHQwk18FYyGSsf9FRUbPAKtTN4T4ICBRON5P9FaFPFIFDHnil9Tbv8pIMGIQjp/aopnvjXS4le/TgN254CMAW6y6p5UUOb5J/5zJ/e5MpO4SSAhf0xBCwrxLJqXQPA93tD2pzsE/hzREqIK8JzTXtR5KtUuc83thMn7jLOjR4av291tqF7UoBUF82TnQ/yIWnP8ZppE/SRcJDhMMu9MbPlxB/qRWiiyCrj6OjDPOpPTQhh3idWFnDECawziQh5A2Z57uUyAmIiIc4+OgHOfVOCkiaL2iDNCODPFtHNoAwsZxM50MbXhMDj9krN+CYvqGwcsoRzpAyOrRB0v5r1acr31/w4M02xRXemOaNtkJnYd6dekkpm5KSsdnMLB3gKZtFI73hOTarZz6hQ/UhQLZV/KYf2WJ6U0u8PWQ=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter