language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: Qy8iv+XCvRtZV3lUYVbP3+xvr4qPZB8L7tdNWRz3yTjYU/vP+TU/508Kn9vWHGSCsHy1E3o0u8q8nD3XaSppik/6QQXaL2YMAEHxyp1PjG5d97WOlidVKbGQASfSFG1MMwNJmRVgmGSACh5T972MdjGw0JrwT9ooH0km3+m9X83ojjB5g1Wo3iqS9njVGpKgAh7lYK/IQCQfZX+upEcLwmcl3SeuzsjY83O5yhlWZe54kaWT+yePTIb4/T6xLyXGuksHnBlALBnysitrJqXgL5I4Ap+2gih4uBJeFE1vczCdohsGlS0/9UziMumzpZlOzViBvgKBSinkr4omDK6B5IFB7LTwUgAhWM4lFta3GbhbHylSWIHWPDVkOE6+++9UpZsQeQuKWaB1iygXt5jwhSZ49L9zznkkZCxYh0Fjk0uuF5VEqixbb/+yz3NhAd03zYWhutQR/Nfj+PV3AYepvnZWLLm+xoDfDQPQXVV0UIJipEeCvGe+28XzqbS/d1N+WHacuoC7cJYkCcl+55/o/7e1MNZrvntqa0JQH6lDdVQh4SMiXHUZFr8oqZ+KN8BTR26beiZMqPoIO2MXZLz+rw8SZ7+9Vb0JxuNrWEzPFKpKrTc6wzwW85T7z6kdhzl37mOrLqWUNYFpcImm69BosnUeLOPELCFBuMZoQJgTbrA=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
