language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: GqX/GmEjujUtOqePHMzkt6GwGezEP6ukRxfxRfNPuhtcIq/mmJK2P2YWtLoP1fERSiD+DqmDttG3mtDPs++EQ/zWS78Xv4Q2XrvZKX+AoQFLyrsOpdcNwjiVUKnL+hSqqeLYd1VjGq6jPbjScDYbjpZubx0oiStMap+uS25py6ZUvUFZc6lJ0B0w72klfawwKhq4Nfgg/mjHyhdRoTatFVCAm9x5PhW4g3VNEZz2hUXqFNvWePanjCgNuc0FKEqQdOyCnsBreWMckzIWY4m8SmuEw2EBHa2bIB1nsm+iC6fXcB3bAAN5/HmSVAgXU7WGSxsjzsUwigmT5DFoHBmVm5NuyrM5jyB5xQI9cWrzA1QOVBgNbqshJVe01M3n6WSmJpPlleeObK77bQTSK4mkFSvvg99f5m8GFwAhzaQsCrfgo2zMvdcFsD2ikiB8o1r/h+1fzzGAan2cAukFar3koI/r+r+/eYBqHF/9oPmcPxCTUrLqMmn4cHnArxj5lApM22tVyG6dzv2bfHsnUvb9z/nugOX+Ln5ugfv8/aSk1Um4XPWyOlMA7payNLdgV6+PqW6647jOTIJOZ63LqJw7LJvpSUvTAc57VGf++4OBq437au6L65omnteZDXo+cGz+128luTbcH0WsRRWWfBPkCgkyYYl6IFhM6YWzc7FSETc=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
