language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: BU06R3kDIqHZM95crTDwbJ8Ysq3clinn8dwcMCRq/8xJUC9ou3j0hGoHK5aW4TOQva2Bs3Ot9t+OhkKySHvEJZ+K0kkZZ7AgB36gZmKx77wxB0QjyFCn4Xk7lT4iQnmcKpEBsgwGYR6o6xhuxDLDUYL5VjjWWDZ4jffZoxZXugHVg0ygjMnkCilCYyq+wqWsWKcr1SqWO/tRbtcTFllqqAttuZN9Rua6MwCjA5n//XZyniE3cnLZDgooVm74vttb2iXy8IEYD9AF+A1YxACCJbZrIhIC2dx8rPz5KFvD29OTtQ+ZzzvGL3PZdr2pqetHLZR3vgaT4vzdgi3vUohJZ5yfLDTOeTTfwx+vFWlH7NnEkZJTidns+E9TgBlau/1sVLd9QAm0HkTeBUSFyV5uTKLByCFYc8wVjvpnI7E9JUQyzFGsFYfpoCOMIUmru4JmXQAAnx145xmCCPei9Mzp4sIlDZaH4MHCVFJh8WO+oi1pdB+y4ASvK/LXwMIjhpsi/7MVDLdv6GdKUTJdqag5W7j4rAk0TtxWpRYeYLEQz80wYYaEC8CXJmAWiiuwbSRfZ8B58nhUsIj/Q4nOZDB7gI3TYWG2OB1/RIZDoXasBoxwENBDQgMKolzCzPuGrb0sl1moiy4C5ZcbQfBxXupkxSExADuxd+oyy4SeSuEsBcs=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
