language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: kizjZ1LT1+LFKz/yZZhUsdWFZaML1eedRqgeHEYjX+wFNTVDj4kfKGrumtFD+UAhA4AUPuhjNJtTNCHTWFZlr91ZKMre5LQSvSxiw1IGCwduZZ0PsefU2l2/GZ/PqOLiDpo/qSykbuvSmPvDuuO1H9jQChP9PNLwQOjWcNRJCEhu2BUfJpyIwdFuUuftbUOTS+mRfu30fW+qmwRcUmn/qEquAOm5o1z4A8C1Oe4P8D2Xkb2qYIpDheb7J6ZPo/tXObKkfeC0sAt9Fl8K+gIhifhbMBJpaNzdL38t2Cl7GG/A4B9EBeogmn7np0r8+f3UsBJ94zOAzRgMsnmAF7BFanQU++emuDhsFs3yzFVrY6gNMOXEEIb0CtYadqmdjrqTZR3c8tL+YDe2dk4QQQ5mRG4xQPrJM9YNtd+EWWvxXyf2K+pQP1vhKoQYaqMCr/Hq+StN+yh3VmBBFjFLqeDyJ/Pe419DE/6i3S/P2u8HVxAZmkCYCidYtTbbad6DE6Rrq2neZ4DJtflsUhIKE7DSjQ9h4QbgZR9E44hOUPy8C59eCjTIao5s88DKm3Q3R3yw0EefaLocKaIbHOY0RxXI+kwrV0Hb3zUl0QXRkfxnr9bK5e/DOKmZ0sF0s4JceQP8iYW8DXjHHYzvWdfIfXhzw8CFx9HmPVq4IUtn6ZK7fIA=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter