language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: dus/JRnC7iZ7b4h+3kKuB44b/q2cI8EIJoYlkF4jPWQjlPcZLwOu1IA8JPXUgFBtSRD5a+rsmQprlDAHwgoEgtXff80cgR0ZzuPtHh+ERFLM1hAIiQXJluyPAkMvbFoonmypZAcNEdU3h32hX4L4n2nS0sq3oums40HoOy1TzNQvOJkEzoAofPSDBzvJz4tiOjM95TJqV69r9ZBCHozt4UojhVimm0N1S1DzGLJgfeJ/CxoDf7OiTRhqJIKnKE45QcymJN+6/NrASaFjZDFnNV+i67/6Buy/80Sik7EpgkY/EOZk11evoM42uDbGeF1/gY10SuhyUoOHBWe7ls+MwT89IgvvXHEihw9TCC7u7F0fXT8SA8MNTsYjSc7W/zhU4XbbXvQywZUl7EfUYB4mv+fvf8CuQqyZvgu08hi4rDfm73lJHAfYS1/jYacgt1BXUT1Pcl7cRk2R4ZhOAz/aFOhQZZDRqeG6RtQ2tfRnwss2u9xl98OvXuO82hcTxQ1epu0pKreFmtrqKVRwyEQB+DM+1YPSOLaLJiaN9vEwmKJRDc6GUs0E6YOJv9rPLZmh+eug94Jy/lq6L40J4bTXXj2yxAs1fwgonS451z62n80e33meuiP9pkDLbUR67w4IEjaVpOKHrmw/q+Kw2NtD95yqdwDtN9MCzxY3a83benA=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
