language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
     secure: "WxlPlk0cj51RRyiUik6RW654kS7FQqW4ucvzg8rKpqgzLXcaeymyPcMvt1JTF+GfzyYOYe49kvQfUCJFwyeye+YM8abWEJ6wWk3psrQPfgwGnO+KCf6XEt4LfiGdGA4xKVPkAaaJhHmf62IpAgTI4/JXogEkxOzlvq0eLT1yhxz2S1bH9fWCQOnpQgt4Ke6nJce8UxPAvvt4frli/QrJJZt38Zbzabu96rpQtB4mtPE0P6hZ/f68f+cf8t1vlOoMJuwHOfZNHEdphBm0DQIGYC9SdHdfBmkVd/vIyTpC0/TcaDQqQOELI5e3qVKTZ52WtRkt6GjYcOJw8o9YmJUbTfsxi/pWvqJPEiHIF46VNT4T4szGtMmkPvwC3/F5nbKQjRazLBOfSYJL0SN+Di3L7u1N5OXsBFfqr6NXmTvXfqLQfyFkVupkbhzK3s4yUlbU7zA1+9iROtceV6SydGPWYid/bWd3c4q/M7vRY/tYN5SYjpT6aEcaIp2rTUL4sf3yh6PH+y72fCpNNPTCja4OLyfaym4VmpRHmFVo093KN5Y9bAceR9LIaQ5fft5RedgcLlKDNkbKw7gYnT9LI39ZZ77T12sKo4DZyOD2V1E96Y5QVQbJUwlMfYemiT2mYr+q5TREged7x+/3G6XX78sFwfEADRxIqxukFWRsP7uGfPk="