language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: BZz6w2BEi6ezzIFEpIDrqYuk3St561upKtlDZe8hj1i4T8QcBzUep7fPiyhQyt6K8aUsRxkd8t31BqVMUP+4G97vbhA4BHTDZk35nEMVxiIji7iKpLr2Dp9yKJo8CVq7huJOqjmcU7W7xN1bp1c/UOcMlqRXvL/v2ZxY4PHMvXbtIPVHlPyAlE84AvXZagEl0MG7KQxCNhb7W1MfMvvHuFcnE+FbjpFcpHDdvwWuN3px97ouZafY8GmIKHoer6foVNsoCnN1q3mosJJjxfRpCWxQszHqqyPjb5SLLko7BSfUcJInxJq4jSRqjIZjVyYHl0jiORjWacUC3fXiVwThGh3TgRsnHH7BlvT+ZfiqQeorgBPdMa/guah2PKH97zfgSec+bP+Tksc4nKykri5pRbJPiXytgh1cRgQNWJsbDEscEgh8idLnqS1NhRGprlsbVA2XwjUzSj7yU0AZrJFCmk/OLwS1kKK+SEaY6NgKG0FZvqp2+5kfes1vmAXBz0hPx59AoVKP8CWHHYlNk3G5z9SHyykIj9ickyIDiuFTIEIOFVZeFWog0GoMItDuSfp0SXRJIFk5U9IhpHFIaSIYHH5esvzyC260Blj17/TFwJmIy6gwEwNPY2HfV8I8lLX7/8AQOU8PiZlvySHdD9PeVf79aLblbJguO37KaOJ3+tI=
