language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: PO7e3qOnk0bQfDMizFSbQRk6nhpQ4vekptickDrbnBvpI9u48Ng+sIYfDHS9/Gm9y1a0moyioWXxWG5CLggolNJo2pNxKPqwya5Nui6YrlqllOuoz5R4O4MD4mt55iGzmcXPkNNvlNtOI93KyiKWYkT8QHYpG9Qv8VwZBQ37ugX094bkAKSw5xipxzs8WiQB+HrdPui2ABCc7xjzRQhi1tZOyDmq4h9/o/Y/oSmFVCNQUZ+My9K5Wl3HozXf/Aed0LJpwz9t/1wwz3YQeP0UHZxN1n+92tEUWh+QiON9R5G9oUFVXjdoO9xRGpZ8TKireBoGf/c4I/eCPj0IauK0DX8fq6XSdr/lidVyZgF33jI5bkNPO2wJsUbNIGwVotTpoALFDq9H9D4jLPL5zjKv1g4A4haEfQ3AoQoAL8m9kDD84vXmpYyVlcC0eJkIfbMrH2DaB9Jy4x04FdNynJOyaO72YZecDk+xXNEK8Iy5pTikxNHCFKtxlr1eYme5dKbU8ox1WbIoqjLXT1oLdjgeS0jq9/MxI6yH1YpMRSc7FhJLKhV+DHLPZyu1oRe7XRuyBqY4oqWDf3SL8BLVM4sqa2WRJ8Rqpg16WQn0hMg2z1B1VZn9c9AVQ/OTuu3sG/B00HQNBPTMvdR3ZVecoK6bNbhB9Kh4cE3zgl45l5wi5NE=
  app: currency-converter
  on:
    repo: jrbarrio/currency-converter
